### ISSUE TITLE
Failing on v0.3 (using gc_enable)

### ISSUE THREAD

**Issue by slundberg** [JuliaLang/GZip.jl#30]
After the latest update the following code fails because `close` calls `gc_enable` with a Bool argument, which I think is only supported on the master version of Julia right now. Not sure what the version support goals are for GZip, but I thought I should mention this for others who run into it.

```julia
f = GZip.open("/tmp/test", "w")
close(f)
```

**Comment by yuyichao** [comment]
Which version of `Compat.jl` are you using, these should be [defined by `Compat.jl`](https://github.com/JuliaLang/Compat.jl/blob/d12d6fb3951707c78abb0fb2391d6f4e28e3398f/src/Compat.jl#L476)

**Comment by yuyichao** [comment]
The current version of these definition is added in https://github.com/JuliaLang/Compat.jl/commit/aec96b7952ec366c8d2e9f26abfe92621a9f4849 and according to github they should be available in `Compat.jl` `0.4.8` and later

**Comment by slundberg** [comment]
Ah! My mistake...I realize now I had an old version of Compat loaded in the Julia session from before the last Pkg.update() run. Sorry to mis-report this.

**Comment by kmsquire** [comment]
Would be good to set the minimum version of Compat to 0.4.8.  (I'll do that.)
